name: Python unit-testing and ruff linting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v10.2.0
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync --frozen

    - name: Lint with Ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run ruff check --config pyproject.toml

    - name: Test unittests
      env:
        CI: "true"
      run: |
        env | grep -E 'CI|TZ'

        TZ=UTC uv run pytest tests --disable-warnings

        TZ=Europe/Copenhagen uv run pytest tests --disable-warnings
